Resources:
  # Creates the StoreHoursTable DynamoDB resource
  # ref: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html
  StoreHoursTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: ${self:provider.environment.todosTable}
      AttributeDefinitions:
        - AttributeName: userName
          AttributeType: S
        - AttributeName: createTime
          AttributeType: N
      KeySchema:
        - AttributeName: userName
          KeyType: HASH
        - AttributeName: createTime
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
